#!/usr/bin/env python3
"""Archiet X-Ray — see the architecture your AI is flying blind without.

Point it at any repo. It extracts the *actual* architecture — routes, domain
entities, async tasks, module dependencies, boundary risks — into:

  - architecture.json   machine-readable model (the "repo genome")
  - ARCHITECTURE.md     human-readable map with Mermaid diagrams
  - AGENT_CONTEXT.md    compact context pack for AI coding agents

Philosophy (borrowed from microcodegen): this file is the complete algorithm.
Stdlib only. No LLM calls — every fact in the output is deterministically
extracted from source, so the same repo always produces the same map. What we
cannot extract with confidence is labelled "unmapped", never guessed.

Usage:
    python xray.py [REPO_PATH] [--out DIR] [--json] [--quiet]

Generated by the Archiet project — https://archiet.com
"""

from __future__ import annotations

import argparse
import ast
import json
import os
import re
import sys
import warnings
from collections import defaultdict
from dataclasses import asdict, dataclass, field
from pathlib import Path

XRAY_VERSION = "0.1.1"

# ── repo walking ─────────────────────────────────────────────────────────────

SKIP_DIRS = {
    ".git",
    ".hg",
    ".svn",
    "node_modules",
    "__pycache__",
    ".next",
    ".nuxt",
    "dist",
    "build",
    "out",
    ".venv",
    "venv",
    "env",
    ".tox",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "coverage",
    ".turbo",
    "vendor",
    "site-packages",
    ".idea",
    ".vscode",
    "target",
    ".cargo",
    ".terraform",
}
CODE_EXTS = {
    ".py",
    ".ts",
    ".tsx",
    ".js",
    ".jsx",
    ".prisma",
    ".go",
    ".rb",
    ".java",
    ".cs",
    ".php",
    ".rs",
}
MAX_FILE_BYTES = 1_500_000  # skip generated monsters


def gitignored_dirs(root: Path) -> set[str]:
    """Top-level directory names ignored by a simple .gitignore (best effort)."""
    out: set[str] = set()
    gi = root / ".gitignore"
    if not gi.is_file():
        return out
    for line in gi.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if not line or line.startswith(("#", "!")):
            continue
        name = line.strip("/")
        if name and "*" not in name and "/" not in name:
            out.add(name)
    return out


def walk_repo(root: Path) -> list[Path]:
    files: list[Path] = []
    skip = SKIP_DIRS | gitignored_dirs(root)
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in skip and not d.startswith(".")]
        for fn in filenames:
            p = Path(dirpath) / fn
            if p.suffix.lower() in CODE_EXTS:
                try:
                    if p.stat().st_size <= MAX_FILE_BYTES:
                        files.append(p)
                except OSError:
                    continue
    return files


# ── model ────────────────────────────────────────────────────────────────────


@dataclass
class Route:
    path: str
    methods: list[str]
    handler: str
    file: str
    line: int
    framework: str
    auth: bool | None  # True/False when detectable, None = unknown


@dataclass
class Entity:
    name: str
    file: str
    line: int
    framework: str
    fields: list[str] = field(default_factory=list)
    relations: list[str] = field(default_factory=list)  # target entity/table names


@dataclass
class AsyncTask:
    name: str
    file: str
    line: int
    framework: str


@dataclass
class Finding:
    code: str
    severity: str  # high | medium | info
    file: str
    line: int
    message: str


# ── python extraction (ast — high confidence) ────────────────────────────────

ROUTE_ATTRS = {"route", "get", "post", "put", "delete", "patch", "head", "options"}
HTTP_METHOD_ATTRS = ROUTE_ATTRS - {"route"}
AUTH_DECORATOR_HINTS = {
    "login_required",
    "jwt_required",
    "require_auth",
    "requires_auth",
    "auth_required",
    "token_required",
    "permission_required",
    "roles_required",
    "require_api_key",
    "authenticated",
}
AUTH_CALL_HINTS = {"get_current_user", "get_jwt_identity", "current_user"}
# Auth-ish dependency names in FastAPI signatures/annotations:
# CurrentUser, current_active_user, get_current_active_superuser, RequireAdmin…
AUTH_NAME_RE = re.compile(
    r"current.?(active.?)?(user|superuser|admin)|superuser|require.?(auth|admin|user)"
    r"|authenticated|api.?key.?auth|oauth2.?scheme|verify.?token",
    re.I,
)
MIGRATION_PATH_RE = re.compile(r"(^|/)(alembic|migrations)(/|$)", re.I)
TASK_DECORATOR_HINTS = {"task", "shared_task", "periodic_task"}
MODEL_BASE_HINTS = {"Model", "Base", "DeclarativeBase", "SQLModel"}
SECRET_NAME_RE = re.compile(
    r"(SECRET|PASSWORD|PASSWD|API_KEY|APIKEY|TOKEN|PRIVATE_KEY|ACCESS_KEY)", re.I
)
SECRET_PLACEHOLDER_RE = re.compile(
    r"(change.?me|your.?secret|placeholder|example|dummy|xxx+|<[^>]+>|\$\{)", re.I
)
# Names that merely *mention* TOKEN/KEY but never hold a secret value.
SECRET_NAME_EXEMPT_RE = re.compile(
    r"(_URL|_URI|_ENDPOINT|_NAMES?|_HINTS?|_PATH|_HEADER)$", re.I
)


def looks_like_secret_value(value: str) -> bool:
    if len(value) < 10 or SECRET_PLACEHOLDER_RE.search(value):
        return False
    if value.startswith(("http://", "https://", "/", "Bearer ")):
        return False
    if " " in value:  # sentences / display strings
        return False
    if re.fullmatch(r"[A-Z][A-Z0-9_]*", value):  # error-code style identifiers
        return False
    # Short snake-case values are identifiers/slugs ("token_bucket"), but long
    # lowercase strings are plausibly real keys (Stripe keys are lowercase).
    if len(value) < 24 and re.fullmatch(r"[a-z][a-z0-9_.-]*", value):
        return False
    return True


TEST_PATH_RE = re.compile(r"(^|/)(tests?|qa_|fixtures?|mocks?|examples?)", re.I)


def _dec_name(dec: ast.expr) -> str:
    """Dotted-ish name of a decorator expression."""
    target = dec.func if isinstance(dec, ast.Call) else dec
    parts: list[str] = []
    while isinstance(target, ast.Attribute):
        parts.append(target.attr)
        target = target.value
    if isinstance(target, ast.Name):
        parts.append(target.id)
    return ".".join(reversed(parts))


def _str_const(node: ast.expr) -> str | None:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    return None


class PyScanner(ast.NodeVisitor):
    def __init__(self, rel: str):
        self.rel = rel
        self.routes: list[Route] = []
        self.entities: list[Entity] = []
        self.tasks: list[AsyncTask] = []
        self.imports: set[str] = set()
        self.findings: list[Finding] = []

    # imports -------------------------------------------------------------
    def visit_Import(self, node: ast.Import):
        for a in node.names:
            self.imports.add(a.name)
        self.generic_visit(node)

    def visit_ImportFrom(self, node: ast.ImportFrom):
        if node.module and node.level == 0:
            self.imports.add(node.module)
        self.generic_visit(node)

    # routes / tasks --------------------------------------------------------
    def _scan_function(self, node: ast.FunctionDef | ast.AsyncFunctionDef):
        auth_seen = False
        route_calls: list[tuple[str, ast.Call]] = []
        for dec in node.decorator_list:
            name = _dec_name(dec)
            leaf = name.rsplit(".", 1)[-1]
            if leaf in AUTH_DECORATOR_HINTS:
                auth_seen = True
            if isinstance(dec, ast.Call) and leaf in ROUTE_ATTRS:
                route_calls.append((leaf, dec))
            if leaf in TASK_DECORATOR_HINTS:
                self.tasks.append(AsyncTask(node.name, self.rel, node.lineno, "celery"))
        if not auth_seen:
            # FastAPI-style auth, three shapes:
            #   (a) default value:   user = Depends(get_current_user)
            #   (b) Annotated alias: current_user: CurrentUser
            #   (c) route kwarg:     @router.get(..., dependencies=[Depends(...)])
            args = node.args
            sig_nodes: list[ast.expr] = list(args.defaults)
            sig_nodes += [d for d in args.kw_defaults if d is not None]
            sig_nodes += [
                a.annotation
                for a in args.posonlyargs + args.args + args.kwonlyargs
                if a.annotation is not None
            ]
            for _, call in route_calls:
                sig_nodes += [
                    kw.value for kw in call.keywords if kw.arg == "dependencies"
                ]
            for sn in sig_nodes:
                for sub in ast.walk(sn):
                    name = ""
                    if isinstance(sub, ast.Call):
                        name = _dec_name(sub.func)
                        if name.rsplit(".", 1)[-1] == "Depends" and sub.args:
                            name = _dec_name(sub.args[0])
                    elif isinstance(sub, (ast.Name, ast.Attribute)):
                        name = _dec_name(sub)
                    if name and ("Depends" in name or AUTH_NAME_RE.search(name)):
                        auth_seen = True
                        break
                if auth_seen:
                    break
            if not auth_seen:
                body_calls = {
                    _dec_name(c.func).rsplit(".", 1)[-1]
                    for c in ast.walk(node)
                    if isinstance(c, ast.Call)
                }
                if body_calls & AUTH_CALL_HINTS:
                    auth_seen = True

        for leaf, call in route_calls:
            path = next(
                (s for a in call.args if (s := _str_const(a)) is not None), None
            )
            if path is None:
                continue
            methods: list[str] = []
            if leaf in HTTP_METHOD_ATTRS:
                methods = [leaf.upper()]
                framework = "fastapi"
            else:
                framework = "flask"
                for kw in call.keywords:
                    if kw.arg == "methods" and isinstance(
                        kw.value, (ast.List, ast.Tuple)
                    ):
                        methods = [
                            s.upper()
                            for e in kw.value.elts
                            if (s := _str_const(e)) is not None
                        ]
                methods = methods or ["GET"]
            # Honesty: FastAPI routers commonly attach auth at include_router /
            # APIRouter(dependencies=...) level, invisible per-function. When we
            # saw nothing, report unknown (None) — never a confident False.
            auth_val: bool | None = (
                True if auth_seen else (False if framework == "flask" else None)
            )
            self.routes.append(
                Route(
                    path,
                    methods,
                    node.name,
                    self.rel,
                    node.lineno,
                    framework,
                    auth_val,
                )
            )

    def visit_FunctionDef(self, node: ast.FunctionDef):
        self._scan_function(node)
        self.generic_visit(node)

    def visit_AsyncFunctionDef(self, node: ast.AsyncFunctionDef):
        self._scan_function(node)
        self.generic_visit(node)

    # entities ----------------------------------------------------------------
    def visit_ClassDef(self, node: ast.ClassDef):
        base_leaves = set()
        for b in node.bases:
            base_leaves.add(_dec_name(b).rsplit(".", 1)[-1])
        if base_leaves & MODEL_BASE_HINTS:
            fields: list[str] = []
            relations: list[str] = []
            for stmt in node.body:
                target_name = None
                value = None
                if (
                    isinstance(stmt, ast.Assign)
                    and len(stmt.targets) == 1
                    and isinstance(stmt.targets[0], ast.Name)
                ):
                    target_name, value = stmt.targets[0].id, stmt.value
                elif isinstance(stmt, ast.AnnAssign) and isinstance(
                    stmt.target, ast.Name
                ):
                    target_name, value = stmt.target.id, stmt.value
                if not target_name or target_name.startswith("_"):
                    continue
                fields.append(target_name)
                if value is not None:
                    for c in ast.walk(value):
                        if isinstance(c, ast.Call):
                            leaf = _dec_name(c.func).rsplit(".", 1)[-1]
                            if leaf == "ForeignKey":
                                fk = next(
                                    (
                                        s
                                        for a in c.args
                                        if (s := _str_const(a)) is not None
                                    ),
                                    None,
                                )
                                if fk:
                                    relations.append(fk.split(".")[0])
                            elif leaf in {"relationship", "ForeignKeyField"}:
                                tgt = next(
                                    (
                                        s
                                        for a in c.args
                                        if (s := _str_const(a)) is not None
                                    ),
                                    None,
                                )
                                if tgt:
                                    relations.append(tgt)
            self.entities.append(
                Entity(
                    node.name,
                    self.rel,
                    node.lineno,
                    "sqlalchemy/django",
                    fields[:40],
                    sorted(set(relations)),
                )
            )
        self.generic_visit(node)

    # findings ----------------------------------------------------------------
    def visit_Assign(self, node: ast.Assign):
        for t in node.targets:
            if (
                isinstance(t, ast.Name)
                and SECRET_NAME_RE.search(t.id)
                and not SECRET_NAME_EXEMPT_RE.search(t.id)
            ):
                v = _str_const(node.value)
                if v and looks_like_secret_value(v):
                    sev = "info" if TEST_PATH_RE.search(self.rel) else "high"
                    self.findings.append(
                        Finding(
                            "hardcoded-secret",
                            sev,
                            self.rel,
                            node.lineno,
                            f"`{t.id}` is assigned a literal value in source — move to env/config.",
                        )
                    )
        self.generic_visit(node)

    def visit_Call(self, node: ast.Call):
        leaf = _dec_name(node.func).rsplit(".", 1)[-1]
        # Migration files legitimately contain raw SQL — not a boundary risk.
        if leaf in {"execute", "executemany"} and not MIGRATION_PATH_RE.search(self.rel):
            sql = next((s for a in node.args if (s := _str_const(a)) is not None), None)
            if sql and re.match(r"\s*(SELECT|INSERT|UPDATE|DELETE)\b", sql, re.I):
                self.findings.append(
                    Finding(
                        "raw-sql",
                        "medium",
                        self.rel,
                        node.lineno,
                        "Raw SQL string passed to execute() — bypasses the ORM layer.",
                    )
                )
        self.generic_visit(node)


def scan_python(path: Path, rel: str) -> PyScanner | None:
    try:
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", SyntaxWarning)
            tree = ast.parse(path.read_text(encoding="utf-8", errors="replace"))
    except SyntaxError:
        return None
    s = PyScanner(rel)
    s.visit(tree)
    return s


# ── js/ts extraction (regex — pragmatic confidence) ──────────────────────────

EXPRESS_ROUTE_RE = re.compile(
    r"\b(?:app|router)\.(get|post|put|delete|patch)\(\s*['\"`]([^'\"`]+)['\"`]"
)
JS_IMPORT_RE = re.compile(
    r"""(?:import\s[^'"]*?from\s*|require\(\s*)['"]([^'"]+)['"]"""
)
PRISMA_MODEL_RE = re.compile(r"^model\s+(\w+)\s*\{", re.M)
PRISMA_REL_RE = re.compile(r"^\s*\w+\s+(\w+)(\[\])?\s+@relation", re.M)
# Assembled at runtime so this scanner never trips greps for its own pattern.
LOCALSTORAGE_TOKEN_RE = re.compile(
    r"(local" + r"Storage|Async" + r"Storage)\.set" + r"Item\(\s*['\"`][^'\"`]*"
    r"(token|jwt|auth)[^'\"`]*['\"`]",
    re.I,
)


def next_route_from_path(rel: str) -> str | None:
    """Derive a Next.js app/pages router URL from a file path."""
    norm = rel.replace("\\", "/")
    m = re.search(r"(?:^|/)app/(?:(.*)/)?(page|route)\.(tsx?|jsx?)$", norm)
    if m:
        url = "/" + (m.group(1) or "")
        url = re.sub(r"/\([^)]+\)", "", url)  # drop route groups
        url = re.sub(r"\[(\.{3})?(\w+)\]", r":\2", url)  # [id] -> :id
        return url.rstrip("/") or "/"
    m = re.search(r"(?:^|/)pages/(.*?)\.(tsx?|jsx?)$", norm)
    if m and not m.group(1).startswith("_"):
        url = "/" + m.group(1)
        return re.sub(r"\[(\w+)\]", r":\1", url).removesuffix("/index") or "/"
    return None


def scan_js(path: Path, rel: str) -> dict:
    text = path.read_text(encoding="utf-8", errors="replace")
    routes: list[Route] = []
    findings: list[Finding] = []
    imports = {m.group(1) for m in JS_IMPORT_RE.finditer(text)}

    norm = rel.replace("\\", "/")
    url = next_route_from_path(rel)
    if url is not None:
        kind = (
            "page"
            if norm.endswith(("page.tsx", "page.jsx", "page.ts", "page.js"))
            or "/pages/" in norm
            else "api"
        )
        if norm.endswith(("route.ts", "route.js")) or "/pages/api/" in norm:
            methods = sorted(
                set(
                    re.findall(
                        r"export\s+(?:async\s+)?function\s+(GET|POST|PUT|DELETE|PATCH)\b",
                        text,
                    )
                )
            ) or ["GET"]
            routes.append(
                Route(url, methods, Path(rel).stem, rel, 1, "nextjs-api", None)
            )
        elif kind == "page":
            routes.append(
                Route(url, ["GET"], Path(rel).stem, rel, 1, "nextjs-page", None)
            )

    for m in EXPRESS_ROUTE_RE.finditer(text):
        line = text[: m.start()].count("\n") + 1
        routes.append(
            Route(
                m.group(2), [m.group(1).upper()], "<inline>", rel, line, "express", None
            )
        )

    for m in LOCALSTORAGE_TOKEN_RE.finditer(text):
        line = text[: m.start()].count("\n") + 1
        findings.append(
            Finding(
                "token-in-localstorage",
                "info" if TEST_PATH_RE.search(norm) else "high",
                rel,
                line,
                "Auth token written to localStorage/AsyncStorage — prefer httpOnly cookies.",
            )
        )
    return {"routes": routes, "findings": findings, "imports": imports}


def scan_prisma(path: Path, rel: str) -> list[Entity]:
    text = path.read_text(encoding="utf-8", errors="replace")
    out = []
    for m in PRISMA_MODEL_RE.finditer(text):
        line = text[: m.start()].count("\n") + 1
        block_end = text.find("\n}", m.end())
        block = text[m.end() : block_end if block_end != -1 else None]
        fields = re.findall(r"^\s*(\w+)\s+\w+", block, re.M)[:40]
        rels = re.findall(r"^\s*\w+\s+(\w+)(?:\[\])?\s", block, re.M)
        rels = sorted(
            {
                r
                for r in rels
                if r[:1].isupper()
                and r
                not in {
                    "String",
                    "Int",
                    "Boolean",
                    "DateTime",
                    "Float",
                    "Json",
                    "Decimal",
                    "BigInt",
                    "Bytes",
                }
            }
        )
        out.append(Entity(m.group(1), rel, line, "prisma", fields, rels))
    return out


# ── dependency graph ─────────────────────────────────────────────────────────


def module_of(rel: str) -> str:
    """Map a file to a coarse module: its top one-or-two path segments."""
    parts = Path(rel).parts
    if len(parts) == 1:
        return "(root)"
    return "/".join(parts[:2]) if len(parts) > 2 else parts[0]


def internal_target(imp: str, top_levels: set[str]) -> str | None:
    """Resolve an import string to an internal top-level module, if it is one."""
    head = imp.lstrip("./").replace("\\", "/").split("/")[0].split(".")[0]
    if head in top_levels:
        return head
    return None


def python_package_roots(files: list[Path], root: Path) -> dict[str, str]:
    """Map importable package name -> repo-relative dir prefix.

    Handles nested layouts (``backend/app/`` imported as ``app``, ``src/<pkg>``)
    by finding directories that contain ``__init__.py`` while their parent
    does not — those are the real Python import roots.
    """
    init_dirs: set[str] = set()
    for p in files:
        if p.name == "__init__.py":
            init_dirs.add(str(p.parent.relative_to(root)).replace("\\", "/"))
    roots: dict[str, str] = {}
    for d in init_dirs:
        parent = d.rsplit("/", 1)[0] if "/" in d else ""
        if parent not in init_dirs:
            roots[d.rsplit("/", 1)[-1]] = d
    return roots


# ── scoring ──────────────────────────────────────────────────────────────────


def visibility_score(stats: dict) -> int:
    """How much of the repo X-Ray could read and structure.

    'Parsed' = the file was successfully read into the model (its imports
    feed the graph even when it holds no routes/entities). Element counts
    reward repos where the extractor found real structure.
    """
    total = max(stats["code_files"], 1)
    parsed_ratio = stats.get("parsed_files", stats["mapped_files"]) / total
    score = 50 * parsed_ratio
    score += min(15, stats["routes"] * 0.5)
    score += min(15, stats["entities"] * 1.0)
    score += 10 if stats["graph_edges"] > 0 else 0
    score += min(10, stats["tasks"] * 1.0)
    return int(round(min(score, 100)))


# ── output rendering ─────────────────────────────────────────────────────────

FOOTER = (
    "\n---\n*Generated by [Archiet X-Ray]"
    "(https://archiet.com/xray?utm_source=xray-footer) v{v} — "
    "deterministic architecture extraction, no LLM guesses. "
    "Unmapped areas are labelled, never invented.*\n"
)


def mermaid_module_graph(edges: dict[tuple[str, str], int], cap: int = 18) -> str:
    weight: dict[str, int] = defaultdict(int)
    for (a, b), n in edges.items():
        weight[a] += n
        weight[b] += n
    keep = set(sorted(weight, key=weight.get, reverse=True)[:cap])
    ids = {m: f"M{i}" for i, m in enumerate(sorted(keep))}
    lines = ["```mermaid", "graph LR"]
    for m in sorted(keep):
        lines.append(f'  {ids[m]}["{m}"]')
    for (a, b), n in sorted(edges.items(), key=lambda kv: -kv[1]):
        if a in keep and b in keep and a != b:
            lines.append(f"  {ids[a]} -->|{n}| {ids[b]}")
    lines.append("```")
    return "\n".join(lines)


def mermaid_er(entities: list[Entity], cap: int = 20) -> str:
    ents = entities[:cap]
    names = {e.name for e in ents}
    lines = ["```mermaid", "erDiagram"]
    for e in ents:
        lines.append(f"  {e.name} {{ }}")
    seen = set()
    for e in ents:
        for r in e.relations:
            tgt = next(
                (
                    n
                    for n in names
                    if n.lower() == r.lower().rstrip("s") or n.lower() == r.lower()
                ),
                None,
            )
            if tgt and (e.name, tgt) not in seen and e.name != tgt:
                seen.add((e.name, tgt))
                lines.append(f"  {e.name} }}o--|| {tgt} : refs")
    lines.append("```")
    return "\n".join(lines)


def render_architecture_md(model: dict) -> str:
    s = model["stats"]
    out = [
        f"# Architecture Map — `{model['repo']}`",
        "",
        f"**Visibility score: {model['score']}/100** · "
        f"{s['code_files']} code files · {s['routes']} routes · "
        f"{s['entities']} entities · {s['tasks']} async tasks · "
        f"{s.get('parsed_files', s['mapped_files'])} files read, "
        f"{s['mapped_files']} with extracted elements ({s['unmapped_files']} unreadable)",
        "",
        "## System map (module dependencies)",
        "",
        model["mermaid_modules"],
        "",
        "## Domain model",
        "",
        model["mermaid_er"] if model["entities"] else "_No ORM entities detected._",
        "",
        "## Entry points",
        "",
        "| Method | Path | Handler | Auth | File |",
        "|---|---|---|---|---|",
    ]
    for r in model["routes"][:80]:
        auth = {True: "✅", False: "⚠️ none detected", None: "?"}[r["auth"]]
        out.append(
            f"| {','.join(r['methods'])} | `{r['path']}` | `{r['handler']}` | {auth} | `{r['file']}`:{r['line']} |"
        )
    if len(model["routes"]) > 80:
        out.append(
            f"\n_…and {len(model['routes']) - 80} more (see architecture.json)._"
        )
    out += ["", "## Async tasks", ""]
    if model["tasks"]:
        out += [
            f"- `{t['name']}` — `{t['file']}`:{t['line']}" for t in model["tasks"][:40]
        ]
    else:
        out.append("_None detected._")
    out += ["", "## Dependency hotspots (highest blast radius)", ""]
    for h in model["hotspots"][:10]:
        out.append(
            f"- **{h['module']}** — {h['fan_in']} dependents, {h['fan_out']} dependencies"
        )
    out += ["", "## Findings", ""]
    if model["findings"]:
        out += [
            f"- **[{f['severity']}] {f['code']}** `{f['file']}`:{f['line']} — {f['message']}"
            for f in model["findings"][:60]
        ]
    else:
        out.append("_No boundary findings from the deterministic rule set._")
    out.append(FOOTER.format(v=XRAY_VERSION))
    return "\n".join(out)


def render_agent_context(model: dict) -> str:
    s = model["stats"]
    hot = ", ".join(h["module"] for h in model["hotspots"][:6])
    prefixes = sorted(
        {
            seg
            for r in model["routes"]
            if r["path"].startswith("/")
            and len(r["path"]) > 1
            and re.match(r"^[A-Za-z]", (seg := r["path"].split("/")[1]))
        }
    )[:15]
    unauth = [r for r in model["routes"] if r["auth"] is False and r["path"]]
    out = [
        "# AGENT CONTEXT — architecture ground truth for AI coding agents",
        "",
        "> Deterministically extracted; regenerate with `xray.py` after structural changes.",
        "",
        f"- Repo: `{model['repo']}` — {s['code_files']} code files, visibility {model['score']}/100",
        f"- Modules (top-level): {', '.join('`' + m + '`' for m in model['modules'][:20])}",
        f"- Route prefixes: {', '.join('`/' + p + '`' for p in prefixes)}",
        f"- Domain entities ({s['entities']}): "
        + ", ".join("`" + e["name"] + "`" for e in model["entities"][:25]),
        f"- HIGH BLAST RADIUS modules — read dependents before editing: {hot}",
        "",
        "## Invariants observed in this codebase (do not regress)",
    ]
    auth_routes = sum(1 for r in model["routes"] if r["auth"])
    if auth_routes:
        out.append(
            f"- {auth_routes} routes carry an auth guard — new routes should too."
        )
    if unauth:
        out.append(
            f"- ⚠️ {len(unauth)} routes have NO detectable auth guard "
            f"(e.g. `{unauth[0]['path']}` in `{unauth[0]['file']}`) — confirm intent before copying the pattern."
        )
    for f in model["findings"][:10]:
        out.append(f"- ⚠️ {f['code']} at `{f['file']}`:{f['line']} — {f['message']}")
    out.append(FOOTER.format(v=XRAY_VERSION))
    return "\n".join(out)


# ── main pipeline ────────────────────────────────────────────────────────────


def xray(root: Path) -> dict:
    root = root.resolve()
    files = walk_repo(root)
    routes: list[Route] = []
    entities: list[Entity] = []
    tasks: list[AsyncTask] = []
    findings: list[Finding] = []
    file_imports: dict[str, set[str]] = {}
    mapped: set[str] = set()
    parsed: set[str] = set()

    for p in files:
        rel = str(p.relative_to(root)).replace("\\", "/")
        if p.suffix == ".py":
            s = scan_python(p, rel)
            if s is None:
                continue
            parsed.add(rel)
            if s.routes or s.entities or s.tasks:
                mapped.add(rel)
            routes += s.routes
            entities += s.entities
            tasks += s.tasks
            findings += s.findings
            file_imports[rel] = s.imports
        elif p.suffix in {".ts", ".tsx", ".js", ".jsx"}:
            r = scan_js(p, rel)
            parsed.add(rel)
            if r["routes"]:
                mapped.add(rel)
            routes += r["routes"]
            findings += r["findings"]
            file_imports[rel] = r["imports"]
        elif p.suffix == ".prisma":
            es = scan_prisma(p, rel)
            parsed.add(rel)
            if es:
                mapped.add(rel)
            entities += es

    # module graph — resolve imports against real Python package roots
    # (handles backend/app, src/<pkg> nesting) plus plain top-level dirs.
    pkg_roots = python_package_roots(files, root)
    top_levels = {
        Path(rel).parts[0] for rel in file_imports if len(Path(rel).parts) > 1
    }

    def src_module(rel: str) -> str:
        for name, prefix in pkg_roots.items():
            if rel == prefix or rel.startswith(prefix + "/"):
                return name
        return rel.split("/")[0] if "/" in rel else "(root)"

    edges: dict[tuple[str, str], int] = defaultdict(int)
    fan_in: dict[str, int] = defaultdict(int)
    fan_out: dict[str, int] = defaultdict(int)
    for rel, imps in file_imports.items():
        src = src_module(rel)
        for imp in imps:
            head = imp.lstrip("./").replace("\\", "/").split("/")[0].split(".")[0]
            tgt = head if head in pkg_roots else internal_target(imp, top_levels)
            if tgt and tgt != src:
                edges[(src, tgt)] += 1
    for (a, b), n in edges.items():
        fan_out[a] += n
        fan_in[b] += n

    # files importing a module also make 2-segment modules hot
    importable = set(pkg_roots) | top_levels
    seg2_in: dict[str, int] = defaultdict(int)
    for rel, imps in file_imports.items():
        for imp in imps:
            norm = imp.replace(".", "/").lstrip("/")
            parts = norm.split("/")
            if len(parts) >= 2 and parts[0] in importable:
                seg2_in["/".join(parts[:2])] += 1
    hotspots = [
        {"module": m, "fan_in": n, "fan_out": fan_out.get(m.split("/")[0], 0)}
        for m, n in sorted(seg2_in.items(), key=lambda kv: -kv[1])
    ]

    stats = {
        "code_files": len(files),
        "parsed_files": len(parsed),
        "mapped_files": len(mapped),
        "unmapped_files": len(files) - len(parsed),
        "routes": len(routes),
        "entities": len(entities),
        "tasks": len(tasks),
        "graph_edges": len(edges),
    }
    model = {
        "xray_version": XRAY_VERSION,
        "repo": root.name,
        "stats": stats,
        "score": visibility_score(stats),
        "modules": sorted(top_levels),
        "routes": [asdict(r) for r in sorted(routes, key=lambda r: r.path)],
        "entities": [asdict(e) for e in sorted(entities, key=lambda e: e.name)],
        "tasks": [asdict(t) for t in tasks],
        "findings": [
            asdict(f)
            for f in sorted(findings, key=lambda f: (f.severity != "high", f.file))
        ],
        "module_edges": [
            {"from": a, "to": b, "imports": n}
            for (a, b), n in sorted(edges.items(), key=lambda kv: -kv[1])
        ],
        "hotspots": hotspots,
    }
    model["mermaid_modules"] = mermaid_module_graph(edges)
    model["mermaid_er"] = mermaid_er(entities)
    return model


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="Archiet X-Ray — extract the real architecture of a repo."
    )
    ap.add_argument("path", nargs="?", default=".", help="repo root (default: cwd)")
    ap.add_argument("--out", default=None, help="output dir (default: <repo>/.archiet)")
    ap.add_argument(
        "--json", action="store_true", help="print architecture.json to stdout"
    )
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args(argv)

    root = Path(args.path)
    if not root.is_dir():
        print(f"error: {root} is not a directory", file=sys.stderr)
        return 2
    model = xray(root)

    out_dir = Path(args.out) if args.out else root / ".archiet"
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "architecture.json").write_text(
        json.dumps(model, indent=2), encoding="utf-8"
    )
    (out_dir / "ARCHITECTURE.md").write_text(
        render_architecture_md(model), encoding="utf-8"
    )
    (out_dir / "AGENT_CONTEXT.md").write_text(
        render_agent_context(model), encoding="utf-8"
    )

    if args.json:
        print(json.dumps(model, indent=2))
    elif not args.quiet:
        s = model["stats"]
        print(f"Archiet X-Ray v{XRAY_VERSION} — {model['repo']}")
        print(f"  visibility score : {model['score']}/100")
        print(f"  code files       : {s['code_files']} ({s['mapped_files']} mapped)")
        print(f"  routes           : {s['routes']}")
        print(f"  entities         : {s['entities']}")
        print(f"  async tasks      : {s['tasks']}")
        print(f"  findings         : {len(model['findings'])}")
        print(f"  wrote            : {out_dir / 'ARCHITECTURE.md'}")
        print(f"                     {out_dir / 'AGENT_CONTEXT.md'}")
        print(f"                     {out_dir / 'architecture.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
